<a href="https://colab.research.google.com/github/gargi0429/Artificial-Intelligence-/blob/main/Week1_Regression/01_NumPy_Basics/numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
#numpybasics  ## Objectives
- Create NumPy arrays
- Understand shape and dimensions
- Learn indexing and slicing
- Perform basic statistical operations

Author: Gargi Thipase

SyntaxError: invalid syntax (1609790635.py, line 2)

In [26]:
import numpy as np
print("Numpy imported successfully");


Numpy imported successfully


In [12]:
##creating arrays

In [13]:
arr = np.array([10,20,30,40,50])
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [14]:
##shape of array

In [15]:
print("Shape:", arr.shape);

Shape: (5,)


In [16]:
##reshaping arrays

In [17]:
reshaped = arr.reshape(1, 5)
print(reshaped)

[[10 20 30 40 50]]


In [18]:
##Indexing

In [19]:
print("First Element", arr[0])
print("Fourth Element", arr[3])

First Element 10
Fourth Element 40


In [20]:
##Slicing

In [21]:
print(arr[1:4])

[20 30 40]


In [22]:
##Statistical Operations

In [23]:
print("Mean: ", arr.mean())
print("Median: ", np.median(arr))
print("Sum: ", arr.sum())
print("Max: ", arr.max())
print("Min: ", arr.min())



Mean:  30.0
Median:  30.0
Sum:  150
Max:  50
Min:  10


In [24]:
## Summary

Today I learned:

- NumPy array creation
- Shape and reshape
- Indexing and slicing
- Mean, median, sum, max and min functions

SyntaxError: invalid syntax (2922951803.py, line 3)